# Site settings
title: The Wellbeing Collection
client:
  name: Dorset Cereals
  link: https://www.dorsetcereals.co.uk/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Life can be hectic. That’s why we’ve partnered with dorset cereals to help slow things down a touch. Discover handpicked wellbeing escapes, perfect for your digi-detox, outdoor fix, or just because you want a quick getaway, and indulge in those little moments. From refreshing coastal digs to enviable spa retreats, take some time to really enjoy those special adventures, big and small. Discover a world of wellbeing here.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/dorset-wellbeing-collection" # the subpath of the site, including territory and year
img:     "/uk/2020/dorset-wellbeing-collection/_assets/img"
css:     "/uk/2020/dorset-wellbeing-collection/_assets/css"
js:      "/uk/2020/dorset-wellbeing-collection/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed